### PR TITLE
Add space between sed option

### PR DESCRIPTION
**Pull request by pingiun**
This fixed the script on macOS, not sure if this will work with other sed versions.

### CODE REVIEW

**Comment by jamestomasino** [comment]
Sadly, adding a space will work on OSX, but break on many linux systems. Sed is the most frustrating utility for portability, and OSX using a wildly outdated version doesn't help.  I'll keep looking for a perfect solution

**Comment by jamestomasino** [comment]
https://stackoverflow.com/questions/5694228/sed-in-place-flag-that-works-both-on-mac-bsd-and-linux
This outlines the issue. I think the only reasonable ways forward are to either detect the OS and apply a different sed command, like I do for BSD vs GNU `stat` or to explicitly create a .bak file and delete it.

**Comment by pingiun** [comment]
I implemented the platform detection, because that seemed the simplest way to me. This will work on macOS now, but I think other BSD systems also need to be checked.

**Comment by jamestomasino** [comment]
Oh wow. I didn't realize I only used `sed -i` in one spot in the whole program. Neat. This looks like it will work great. Oddly, the issue doesn't occur on other BSDs, just OSX.

**Pull request merged**
